# Generated by Django 2.2.10 on 2020-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_auto_20200107_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, verbose_name='Priority'),
        ),
    ]
