# Generated by Django 2.2.10 on 2020-02-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0029_ticket_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
