# Generated by Django 2.2.10 on 2020-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0031_ticket_other_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_report_type',
            field=models.CharField(blank=True, choices=[('Medical reasons ', 'Medical reasons '), ('No trust in the vaccine provided ', 'No trust in the vaccine provided '), ('No trust in the team providing the vaccines', 'No trust in the team providing the vaccines'), ('Child already vaccinated', 'Child already vaccinated'), ('Based on the recommendation of the pediatric/ physician', 'Based on the recommendation of the pediatric/ physician'), ('Religious reasons', 'Religious reasons'), ('Anti- vaccination movement ', 'Anti- vaccination movement '), ('Other/ specify', 'Other/ specify')], max_length=1500, null=True, verbose_name='Please specify reasons n the narrative as per the following'),
        ),
    ]
