# Generated by Django 2.2.10 on 2020-02-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0032_ticket_sub_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_mohp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_moph', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_unicef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_unicef', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_who', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_report_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Medical reasons ', 'Medical reasons '), ('No trust in the vaccine provided ', 'No trust in the vaccine provided '), ('No trust in the team providing the vaccines', 'No trust in the team providing the vaccines'), ('Child already vaccinated', 'Child already vaccinated'), ('Based on the recommendation of the pediatric/ physician', 'Based on the recommendation of the pediatric/ physician'), ('Religious reasons', 'Religious reasons'), ('Anti- vaccination movement ', 'Anti- vaccination movement '), ('Other/ specify', 'Other/ specify')], max_length=1500, null=True, verbose_name='Please specify reasons n the narrative as per the following'),
        ),
    ]
