# Generated by Django 2.2.10 on 2020-02-12 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0033_auto_20200211_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('UNICEF', 'UNICEF'), ('MoPH', 'MoPH'), ('WHO', 'WHO')], max_length=50, null=True, verbose_name='Assign to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Case owner'),
        ),
    ]
