# Generated by Django 2.2.10 on 2020-02-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0034_auto_20200212_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('pk',), 'verbose_name': 'Queue', 'verbose_name_plural': 'Queues'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='field_focal_person',
            field=models.ForeignKey(blank=True, help_text='Action Points needed at field level ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_person', to=settings.AUTH_USER_MODEL, verbose_name='Field focal person'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='national_focal_person',
            field=models.ForeignKey(blank=True, help_text='Action Points needed at national level ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_person', to=settings.AUTH_USER_MODEL, verbose_name='National focal person'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='other_type',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Please specify'),
        ),
    ]
