# Generated by Django 2.2.10 on 2020-03-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0035_auto_20200215_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Complaint on vaccine storage, provision and disposal', 'Complaint on vaccine storage, provision and disposal'), ("Complaint on vaccinator's skills and visibility (ID/ brand – logo of the campaign should be visible)", "Complaint on vaccinator's skills and visibility (ID/ brand – logo of the campaign should be visible)"), ('Complaint on proper and timely preparation of the community before vaccination', 'Complaint on proper and timely preparation of the community before vaccination'), ('Report on Refusal of vaccination by a community or an institution', 'Report on Refusal of vaccination by a community or an institution'), ('Misconceptions and rumors', 'Misconceptions and rumors'), ('Other challenges or complaints', 'Other challenges or complaints')], max_length=1500, null=True, verbose_name='Report Type'),
        ),
    ]
