# Generated by Django 2.2.10 on 2020-04-07 20:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LASER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('laser_id', models.CharField(max_length=254, unique=True, verbose_name='LASER_ID')),
                ('organization', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Organization Name')),
                ('focal_point_contact', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Focal Point Contact')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief description of objectives')),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Published', 'Published'), ('Discontinued', 'Discontinued'), ('Finalized', 'Finalized'), ('Finalized (but not yet published--To be published as a print profile)', 'Finalized (but not yet published--To be published as a print profile)'), ('Finalized (but not yet published--To be published as an online profile)', 'Finalized (but not yet published--To be published as an online profile)'), ('Finalized; publication underway', 'Finalized; publication underway'), ('Online profile published', 'Online profile published'), ('Online profile published', 'Online profile published')], max_length=1500, verbose_name='Status')),
                ('population_targeted', models.CharField(max_length=1500, verbose_name='Population Targeted')),
                ('sectors_covered', models.CharField(max_length=1500, verbose_name='Sectors covered')),
                ('report_link', models.URLField(blank=True, max_length=1500, null=True, verbose_name='Link to the report')),
                ('required_followup', models.CharField(blank=True, max_length=1500, null=True, verbose_name='If marked as planned or ongoing, when would you like us to follow up with you?')),
                ('published_date', models.DateField(blank=True, max_length=1500, null=True, verbose_name='Published date/Date of last update')),
                ('publication_date', models.DateField(blank=True, max_length=1500, null=True, verbose_name='Date of publication (actual/expected)')),
                ('estimated_cost', models.FloatField(blank=True, help_text='$', null=True, verbose_name='Estimated cost')),
                ('category', models.CharField(blank=True, choices=[('Evaluation', 'Evaluation'), ('Assessment', 'Assessment'), ('Survey', 'Survey'), ('Study', 'Study')], max_length=500, null=True, verbose_name='Category')),
                ('evaluation_type', models.CharField(blank=True, choices=[('Thematic', 'Thematic'), ('UNDAF', 'UNDAF'), ('Country Programme', 'Country Programme'), ('Outcome', 'Outcome'), ('Project', 'Project')], max_length=500, null=True, verbose_name='If evaluation, what type?')),
                ('geographical_focus', models.CharField(blank=True, max_length=500, null=True, verbose_name='Geographical Focus')),
                ('UNSF_outcome', models.CharField(blank=True, max_length=500, null=True, verbose_name='UNSF Outcome')),
                ('section', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section')),
            ],
            options={
                'verbose_name': 'LASER',
                'verbose_name_plural': 'LASER',
                'ordering': ('laser_id',),
                'get_latest_by': 'created',
            },
        ),
    ]
