# Generated by Django 2.2.10 on 2020-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laser',
            name='population_targeted',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Population Targeted'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='sectors_covered',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Sectors covered'),
        ),
    ]
