# Generated by Django 2.2.10 on 2020-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200423_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laser',
            name='laser_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LASER_ID'),
        ),
    ]
