# Generated by Django 2.2.10 on 2020-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200423_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laser',
            name='estimated_cost',
            field=models.CharField(blank=True, default=0.0, help_text='$', max_length=1500, null=True, verbose_name='Estimated cost'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='publication_date',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Date of publication (actual/expected)'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='published_date',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Published date/Date of last update'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='report_link',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Link to the report'),
        ),
    ]
