# Generated by Django 2.2.10 on 2020-05-19 01:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('research_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='RESEARCH_ID')),
                ('title', models.CharField(blank=True, default='No Title', help_text='The full title of the research', max_length=500, null=True, verbose_name='Title')),
                ('publication_year', models.CharField(blank=True, help_text='The year the research was published or made available for public use', max_length=1500, null=True, verbose_name='Year of publication')),
                ('organizations', models.CharField(blank=True, help_text='The organization managing the research', max_length=1500, null=True, verbose_name='Organization(s)')),
                ('researchers', models.CharField(blank=True, help_text='The company or consultant(s) conducting the research', max_length=1500, null=True, verbose_name='Researcher(s)')),
                ('type', models.CharField(blank=True, choices=[('Qualitative', 'Qualitative'), ('Quantitative', 'Quantitative'), ('Mixed', 'Mixed'), ('Desk Review', 'Desk Review')], max_length=500, null=True, verbose_name='Type of research')),
                ('main_sector', models.CharField(blank=True, choices=[('Child Protection', 'Child Protection'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)'), ('Health and Nutrition', 'Health and Nutrition')], max_length=500, null=True, verbose_name='Main Sector')),
                ('geographical_coverage', models.CharField(blank=True, choices=[('Child Protection', 'Child Protection'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)'), ('Health and Nutrition', 'Health and Nutrition')], help_text='A brief narative on the research objectives, methodology, and findings. 250 characters maximum', max_length=500, null=True, verbose_name='Geographical Coverage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description/Abstract')),
                ('report_link', models.URLField(blank=True, help_text='URL link to access the report', max_length=2500, null=True, verbose_name='Link to Report')),
                ('recommendations', models.TextField(blank=True, help_text='Copy and paste or summarize the recommendations that the research study found', null=True, verbose_name='Recommendations')),
                ('planned_actions', models.TextField(blank=True, help_text='Note down the planned action by either UNICEF or any other entity', null=True, verbose_name='Planned Action')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
                'ordering': ('research_id',),
                'get_latest_by': 'created',
            },
        ),
    ]
