# Generated by Django 2.2.10 on 2020-05-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(blank=True, help_text='A brief narative on the research objectives, methodology, and findings. 250 characters maximum', max_length=250, null=True, verbose_name='Description/Abstract'),
        ),
        migrations.AlterField(
            model_name='research',
            name='geographical_coverage',
            field=models.CharField(choices=[('Child Protection', 'Child Protection'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)'), ('Health and Nutrition', 'Health and Nutrition')], max_length=500, verbose_name='Geographical Coverage'),
        ),
        migrations.AlterField(
            model_name='research',
            name='main_sector',
            field=models.CharField(choices=[('Child Protection', 'Child Protection'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)'), ('Health and Nutrition', 'Health and Nutrition')], max_length=500, verbose_name='Main Sector'),
        ),
        migrations.AlterField(
            model_name='research',
            name='organizations',
            field=models.CharField(help_text='The organization managing the research', max_length=1500, verbose_name='Organization(s)'),
        ),
        migrations.AlterField(
            model_name='research',
            name='publication_year',
            field=models.CharField(help_text='The year the research was published or made available for public use', max_length=1500, verbose_name='Year of publication'),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchers',
            field=models.CharField(help_text='The company or consultant(s) conducting the research', max_length=1500, verbose_name='Researcher(s)'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(help_text='The full title of the research', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('Qualitative', 'Qualitative'), ('Quantitative', 'Quantitative'), ('Mixed', 'Mixed'), ('Desk Review', 'Desk Review')], max_length=500, verbose_name='Type of research'),
        ),
    ]
