# Generated by Django 2.2.10 on 2020-05-19 02:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200518_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='planned_actions',
            field=tinymce.models.HTMLField(blank=True, help_text='Note down the planned action by either UNICEF or any other entity', null=True, verbose_name='Planned Action'),
        ),
        migrations.AlterField(
            model_name='research',
            name='recommendations',
            field=tinymce.models.HTMLField(blank=True, help_text='Copy and paste or summarize the recommendations that the research study found', null=True, verbose_name='Recommendations'),
        ),
    ]
