# Generated by Django 2.2.10 on 2020-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200518_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='geographical_coverage',
            field=models.CharField(choices=[('Governorate', 'Governorate'), ('District', 'District'), ('Neighborhood/Village', 'Neighborhood/Village'), ('National', 'National')], max_length=500, verbose_name='Geographical Coverage'),
        ),
        migrations.AlterField(
            model_name='research',
            name='main_sector',
            field=models.CharField(choices=[('Child Protection', 'Child Protection'), ('Health and Nutrition', 'Health and Nutrition'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)')], max_length=500, verbose_name='Main Sector'),
        ),
    ]
