# Generated by Django 2.2.10 on 2020-06-07 21:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20200519_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='taken_actions',
            field=tinymce.models.HTMLField(blank=True, help_text='Note down the taken actions by either UNICEF or any other entity', null=True, verbose_name='Taken Action'),
        ),
        migrations.AlterField(
            model_name='research',
            name='planned_actions',
            field=tinymce.models.HTMLField(blank=True, help_text='Note down the planned actions by either UNICEF or any other entity', null=True, verbose_name='Planned Action'),
        ),
    ]
