# Generated by Django 2.2.10 on 2021-02-08 18:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200607_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('issue_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True, verbose_name='Issue description')),
                ('reported_by', models.CharField(max_length=500, verbose_name='Reported by')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('validated_by_technical_committee', models.BooleanField(blank=True, default=False, verbose_name='Validated by technical committee')),
                ('validated_by_moph', models.BooleanField(blank=True, default=False, verbose_name='Validated by MOPH')),
                ('dissemination_method', models.TextField(blank=True, null=True, verbose_name='Dissemination method')),
                ('relevant_link', models.URLField(blank=True, null=True, verbose_name='Relevant link')),
            ],
            options={
                'ordering': ['issue_number'],
            },
        ),
    ]
