# Generated by Django 2.2.10 on 2021-02-18 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0014_auto_20210208_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infotracker',
            options={'ordering': ['issue_number'], 'verbose_name': 'Concern / Question', 'verbose_name_plural': 'Concerns / Questions'},
        ),
        migrations.AddField(
            model_name='infotracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='infotracker',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
