# Generated by Django 2.2.10 on 2021-02-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20210217_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoTracker',
        ),
    ]
