# Generated by Django 2.2.10 on 2021-02-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_knowledgetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='frequency',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Frequency'),
        ),
    ]
