# Generated by Django 2.2.10 on 2021-03-01 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20210219_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='dissemination_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Community Activity', 'Community Activity'), ('Social Media', 'Social Media'), ('Training', 'Training'), ('Official External Communication', 'Official External Communication')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Dissemination method'),
        ),
    ]
