# Generated by Django 2.2.10 on 2021-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20210301_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='frequency',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Frequency'),
        ),
    ]
