# Generated by Django 2.2.19 on 2021-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20210304_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='other_population_considerations',
            field=models.CharField(choices=[('All', 'All'), ('Elderly', 'Elderly'), ('Pregnant Women', 'Pregnant Women'), ('Breasfeeding Women', 'Breasfeeding Women'), ('People with disabilities', 'People with disabilities'), ('Under 18 ', 'Under 18'), ('People with chronic deseases', 'People with chronic deseases'), ('Social mobilizers: scouts, youth groups, women group, etc...', 'Social mobilizers: scouts, youth groups, women group, etc...'), ('Municipal staff / Crisis cells', 'Municipal staff / Crisis cells'), ('Religious Entities', 'Religious Entities'), ('Frontline workers', 'Frontline workers'), ('Teachers', 'Teachers'), ('NGOs', 'NGOs'), ('CBOs', 'CBOs')], max_length=100, null=True, verbose_name='Other Population Considerations'),
        ),
        migrations.AddField(
            model_name='knowledgetracker',
            name='source_number_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Percentage'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_category',
            field=models.CharField(choices=[('Rumor', 'Rumor'), ('Question', 'Question'), ('Trust issue', 'Trust issue'), ('Transparency', 'Transparency'), ('General Concern', 'General Concern'), ('Pre-registartion', 'Pre-registartion'), ('Vaccine technical questions', 'Vaccine technical questions'), ('Vaccien quality', 'Vaccien quality'), ('Vaccine side effects', 'Vaccine side effects'), ('Access/Service Provision', 'Access/Service Provision')], max_length=50, null=True, verbose_name='Issue Category'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_description',
            field=models.TextField(help_text='40 characters max', null=True, verbose_name='Issue description'),
        ),
    ]
