# Generated by Django 2.2.19 on 2021-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20210317_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='target_population',
            field=models.CharField(choices=[('All', 'All'), ('Lebanese', 'Lebanese'), ('Refugee', 'Refugee'), ('Migrants workers', 'Migrants workers'), ('Stateless population', 'Stateless population'), ('Other Nationality', 'Other Nationality')], max_length=100, null=True, verbose_name='Population Nationality'),
        ),
    ]
