# Generated by Django 2.2.19 on 2021-03-17 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20210317_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='answer',
            field=models.TextField(blank=True, help_text='50 characters max', null=True, verbose_name='Answer/Clarification'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='dissemination_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Community Activity', 'Community Activity'), ('Social Media', 'Social Media'), ('Official External Communication', 'Official External Communication')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Dissemination method'),
        ),
    ]
