# Generated by Django 2.2.19 on 2021-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20210317_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgetracker',
            name='validated_by_moph',
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_category',
            field=models.CharField(choices=[('Question', 'Question'), ('Trust issue', 'Trust issue'), ('Transparency', 'Transparency'), ('General Concern', 'General Concern'), ('Pre-registartion', 'Pre-registartion'), ('Vaccine technical questions', 'Vaccine technical questions'), ('Vaccine quality', 'Vaccine quality'), ('Vaccine side effects', 'Vaccine side effects'), ('Access/Service Provision', 'Access/Service Provision')], max_length=50, null=True, verbose_name='Issue Category'),
        ),
    ]
