# Generated by Django 2.2.19 on 2021-03-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20210319_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='source_number_percentage',
            field=models.TextField(default='%', null=True, verbose_name='Number Percentage'),
        ),
    ]
