# Generated by Django 2.2.19 on 2021-03-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20210319_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='source_number_percentage',
            field=models.CharField(default='%', max_length=5, null=True, verbose_name='Number Percentage'),
        ),
    ]
