# Generated by Django 2.2.19 on 2021-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20210319_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='validated_by_moph',
            field=models.BooleanField(blank=True, default=False, verbose_name='Validated by MOPH'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_category',
            field=models.CharField(choices=[('Rumor', 'Rumor'), ('Question', 'Question'), ('Trust issue', 'Trust issue'), ('Transparency', 'Transparency'), ('General Concern', 'General Concern'), ('Pre-registartion', 'Pre-registartion'), ('Vaccine technical questions', 'Vaccine technical questions'), ('Vaccien quality', 'Vaccien quality'), ('Vaccine side effects', 'Vaccine side effects'), ('Access/Service Provision', 'Access/Service Provision')], max_length=50, null=True, verbose_name='Issue Category'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='source_number_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Percentage'),
        ),
    ]
