# Generated by Django 2.2.19 on 2021-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20210319_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='source_number_percentage',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Number Percentage'),
        ),
    ]
