# Generated by Django 2.2.19 on 2021-03-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_auto_20210319_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgetracker',
            name='validated_by_moph',
        ),
    ]
