# Generated by Django 2.2.19 on 2021-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_remove_knowledgetracker_validated_by_moph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_description',
            field=models.TextField(help_text='50 characters max', max_length=50, null=True, verbose_name='Issue description'),
        ),
    ]
