# Generated by Django 2.2.19 on 2021-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20210326_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='source_relevant_link',
            field=models.URLField(blank=True, null=True, verbose_name='Issue Relevant link'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='source',
            field=models.CharField(choices=[('All', 'All'), ('Poll/Study', 'Poll/Study'), ('Training', 'Training'), ('Community Activity', 'Community Activity'), ('Media', 'Media (TV, radio, etc.)'), ('Social Media', 'Social Media')], max_length=100, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='target_population',
            field=models.CharField(choices=[('All', 'All'), ('Lebanese', 'Lebanese'), ('Refugee', 'Refugee'), ('Migrants', 'Migrants'), ('Stateless population', 'Stateless population'), ('Other Nationality', 'Other Nationality')], max_length=100, null=True, verbose_name='Population / Nationality'),
        ),
    ]
