# Generated by Django 2.2.19 on 2021-05-05 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20210326_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='feedback_color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('grey', 'Grey'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Feedback from Partners'),
        ),
        migrations.AddField(
            model_name='knowledgetracker',
            name='feedback_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('not started', 'Not Started'), ('initiated', 'Initiated'), ('completed', 'Completed')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Feedback from Partners'),
        ),
        migrations.AddField(
            model_name='knowledgetracker',
            name='feedback_text',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Text'),
        ),
    ]
