# Generated by Django 2.2.19 on 2021-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20210505_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='feedback_color',
            field=models.CharField(blank=True, choices=[('grey', 'Grey'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=50, null=True, verbose_name='Feedback color'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='feedback_status',
            field=models.CharField(blank=True, choices=[('not started', 'Not Started'), ('initiated', 'Initiated'), ('completed', 'Completed')], max_length=50, null=True, verbose_name='Feedback from Partners'),
        ),
    ]
