# Generated by Django 2.2.19 on 2021-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20210506_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='feedback_color',
            field=models.CharField(blank=True, choices=[('grey', 'Grey'), ('yellow', 'Yellow'), ('green', 'Green')], default='grey', max_length=50, null=True, verbose_name='Feedback color'),
        ),
    ]
