# Generated by Django 2.2.19 on 2021-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_auto_20210506_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='high_priority',
            field=models.BooleanField(blank=True, default=False, verbose_name='High priority'),
        ),
        migrations.AlterField(
            model_name='knowledgetracker',
            name='answer',
            field=models.TextField(blank=True, help_text='100 characters max', null=True, verbose_name='Answer/Clarification'),
        ),
    ]
