# Generated by Django 2.2.19 on 2021-08-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_auto_20210706_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetracker',
            name='issue_description',
            field=models.TextField(help_text='150 characters max', max_length=150, null=True, verbose_name='Issue description'),
        ),
    ]
