# Generated by Django 2.2.19 on 2021-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20210812_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetracker',
            name='char_save',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowledgetracker',
            name='int_save',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Frequency'),
        ),
    ]
