# Generated by Django 2.2.19 on 2021-08-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_auto_20210812_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgetracker',
            name='char_save',
        ),
        migrations.RemoveField(
            model_name='knowledgetracker',
            name='int_save',
        ),
    ]
